### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by fnberrios** [resfandiari/esp8266_upload_file_multipart-form-data#1]
Hi man! I was trying to implement a code to send a WAV file in a SD to a server as you did, but using a code, base on yours, I get this message.

`file exists
test file:ok
contentLength : 40.54KB
connecting to 192.168.0.2
Connected to server
Requesting URL: /esp32/uploadwav.php
request sent
HTTP/1.1 400 Bad Request
closing connection`

Do you use a PHP file to create de WAV file in the server or with your code is enough to save a WAV in the directory path? I really appreciate any help and nice code by the way. 

(Gracias de antemano mi rey)

**Comment by resfandiari** [comment]
Hey man,
you must set up the server to save the file if you want to do that.
